### PR TITLE
Revamps the configure script

### PR DESCRIPTION
**Pull request by atheriel**
This PR overhauls the autoconf script with a few goals in mind:

1. Removing the things from `gperftools` that we don't actually use (`PRIuS`, `__int64`, and the Solaris compatibility shim, as it turns out).
2. Using the script to locate the `libprofiler` library, first via `pkg-config` but falling back on looking for the actual header files.
3. Using the script to tell users what they need to install on different distros in order to get the installation working.

These changes should make it more palatable to CRAN and easier for users to get installed.

Note that this branch builds and passes checks locally but is *almost certain* to break on CI on the first pass, since I'm unsure of how it will behave on macOS.

Are there other changes that need to be made to the autoconf script, while I'm at it?

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks.

The job did fail on macOS. I started a debug job.

It also failed twice on Linux, I restarted the jobs to double-check. We've been seeing consistent failures for the last few months, so perhaps we'll need to look into these too.

**Comment by krlmlr** [comment]
On macOS, the autoconf script needs to allow headers from `/Users/travis/include` , this is where brew installs gperftools. I'm not familiar with autoconf, but perhaps you have an idea?

**Comment by atheriel** [comment]
We need a way to modify our use of `tic` to do the equivalent of

```console
$ R CMD INSTALL jointprof --configure-vars='CPPFLAGS=-I/Users/travis/include'
```
on macOS. Unfortunately, I haven't figured out how to do that yet.

**Comment by atheriel** [comment]
Got it. This should be ready to review/merge now.

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
